In [3]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of both the variables as given below:

In [12]:
type(list_)

list

In [13]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [20]:
for i in list_:
    print(f"Datatype of {i} in list_ is: {type(i)}")

Datatype of 1 in list_ is: <class 'str'>
Datatype of 2 in list_ is: <class 'str'>
Datatype of 3 in list_ is: <class 'str'>
Datatype of 4 in list_ is: <class 'str'>
Datatype of 5 in list_ is: <class 'str'>


In [19]:
for i in array_list:
    print(f"Datatype of {i} in array_list is: {type(i)}")

Datatype of 1 in array_list is: <class 'numpy.str_'>
Datatype of 2 in array_list is: <class 'numpy.str_'>
Datatype of 3 in array_list is: <class 'numpy.str_'>
Datatype of 4 in array_list is: <class 'numpy.str_'>
Datatype of 5 in array_list is: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [23]:
array_list = np.array(object = list_, dtype = int)

In [25]:
for i in list_:
    print(f"Datatype of {i} in list_ is: {type(i)}")

Datatype of 1 in list_ is: <class 'str'>
Datatype of 2 in list_ is: <class 'str'>
Datatype of 3 in list_ is: <class 'str'>
Datatype of 4 in list_ is: <class 'str'>
Datatype of 5 in list_ is: <class 'str'>


In [26]:
for i in array_list:
    print(f"Datatype of {i} in array_list is: {type(i)}")

Datatype of 1 in array_list is: <class 'numpy.int64'>
Datatype of 2 in array_list is: <class 'numpy.int64'>
Datatype of 3 in array_list is: <class 'numpy.int64'>
Datatype of 4 in array_list is: <class 'numpy.int64'>
Datatype of 5 in array_list is: <class 'numpy.int64'>


the datatype of elements in list_ is same while the datatypes of array_list has been changed from str to int

In [1]:
#Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
1. shape
2. size

In [3]:
num_array.shape

(2, 3)

In [4]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [20]:
nump_array=np.array([[0,0,0],[0,0,0],[0,0,0]])
numpp_array=np.zeros([3,3],dtype=int)

In [22]:
nump_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
numpp_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [24]:
identity_matrix=np.identity(5)

In [25]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])